---
name: 'MY ANALYSIS'

system:
  - module: 'wrapper'
    script: 'model_input/plugins/CHANGE_ME_SYSTEM.py'

engine:
  - module: 'wrapper'
    script: 'model_input/plugins/CHANGE_ME_ENGINE.py'

simulate:
  - times: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

parameters:
  define: 1
  some: 2
  here: 3
