---
# Site information
site_name: flepimop2 Documentation
site_url: https://accidda.github.io/flepimop2/

# Repository information
repo_name: ACCIDDA/flepimop2
repo_url: https://github.com/ACCIDDA/flepimop2
edit_uri: ''

# Theme information
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            heading_level: 2

# Extras
extra:
  version:
    provider: mike

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - mkdocs-click
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      base_path: docs/.
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/branding.css
  - https://unpkg.com/katex@0/dist/katex.min.css

# Navigation structure
nav:
  - Home: index.md
  - Guides:
      - Getting Started: guides/getting-started.md
  - Development:
      - Contributing: development/contributing.md
      - Creating An External Provider Package: development/creating-an-external-provider-package.md
      - Implementing Custom Engines and Systems: development/implementing-custom-engines-and-systems.md
      - Integration Testing: development/integration-testing.md
      - Adding A New CLI Command: development/adding-a-new-cli-command.md
  - Reference:
      - API:
          - Abcs: reference/api/abcs.md
          - Backend: reference/api/backend.md
          - Configuration: reference/api/configuration.md
          - Engine: reference/api/engine.md
          - Exceptions: reference/api/exceptions.md
          - Meta: reference/api/meta.md
          - Module: reference/api/module.md
          - Parameter: reference/api/parameter.md
          - Process: reference/api/process.md
          - Simulator: reference/api/simulator.md
          - System: reference/api/system.md
          - Testing: reference/api/testing.md
          - Typing: reference/api/typing.md
      - CLI: reference/cli.md
  - Changelog: changelog.md
