---
name: 'YAML'

'on':
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  yaml:
    name: 'YAML Lint'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version:
          - '3.12'
    steps:
      - name: 'Install just'
        run: 'sudo apt install just'
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
        with:
          persist-credentials: false
      - name: 'Setup uv'
        uses: 'astral-sh/setup-uv@v7'
        with:
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
          python-version: '${{ matrix.python-version }}'
      - name: 'Run yamllint'
        run: 'just yamllint'
